services:
  - type: web
    name: farmerloan-app
    env: docker
    dockerfilePath: Dockerfile
    plan: free
    healthCheckPath: /
    envVars:
      - key: PORT
        value: 8080
      - key: DB_URL
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
