spring.application.name=Farmerloan

spring.datasource.url=${DB_URL:${SPRING_DATASOURCE_URL:${DATABASE_URL:jdbc:h2:mem:farmerdb;DB_CLOSE_DELAY=-1;MODE=MySQL}}}
spring.datasource.username=${DB_USERNAME:${SPRING_DATASOURCE_USERNAME:sa}}
spring.datasource.password=${DB_PASSWORD:${SPRING_DATASOURCE_PASSWORD:}}
spring.datasource.driver-class-name=${DB_DRIVER:org.h2.Driver}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.h2.console.enabled=true


spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.cache=false
server.port=${PORT:8080}

