spring.application.name=Farmerloan

spring.datasource.url=jdbc:mysql://localhost:3306/farmerdb
spring.datasource.username=root
spring.datasource.password=Admin@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp
server.port=8080

